/* NEXUS PRO · Cliente 360 · prototipo funcional con datos simulados.
   NO escribe en Supabase. Expone nx360Abrir/nx360Cerrar para integración futura. */
(function(){
'use strict';
var clientes=[
{id:'demo-1',nombre:'Juan Pérez',cedula:'001-1234567-8',tel:'809-555-1234',estado:'Al día',saldo:42300,capital:80000,pagado:37700,proxima:'15 Ago',cuota:5000,prestamos:1,polizas:2,equipos:3,facturas:18},
{id:'demo-2',nombre:'Ana Gómez',cedula:'001-7654321-0',tel:'809-555-8910',estado:'En mora',saldo:31500,capital:45000,pagado:13500,proxima:'10 Ago',cuota:4200,prestamos:1,polizas:1,equipos:1,facturas:7},
{id:'demo-3',nombre:'Carlos Martínez',cedula:'402-2211445-1',tel:'829-555-1111',estado:'Al día',saldo:18750,capital:30000,pagado:11250,proxima:'20 Ago',cuota:3750,prestamos:1,polizas:0,equipos:2,facturas:5}
];
var activo=clientes[0],ultimoFoco=null;
function fmt(n){return 'RD$ '+Number(n||0).toLocaleString('es-DO',{minimumFractionDigits:0,maximumFractionDigits:0});}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c];});}
function asegurarCSS(){if(document.getElementById('nx360Css'))return;var l=document.createElement('link');l.id='nx360Css';l.rel='stylesheet';l.href='cliente-360.css';document.head.appendChild(l);}
function markup(){return '<div class="nx360-shell">'+
'<aside class="nx360-side"><div class="nx360-brand">NEXUS PRO<small>Expediente Cliente 360 · Demo visual</small></div><nav><button aria-current="page">Resumen 360</button><button data-tab="financiamiento">Financiamiento</button><button data-tab="pagos">Pagos</button><button data-tab="seguros">Seguros</button><button data-tab="facturas">Facturas</button><button data-tab="equipos">Equipos</button><button data-tab="documentos">Documentos</button></nav></aside>'+
'<main class="nx360-main"><header class="nx360-top"><button class="nx360-btn" data-close aria-label="Volver">← Volver</button><h1>Expediente del Cliente</h1><div class="nx360-grow"></div><button class="nx360-btn primary" data-pay>Registrar pago</button></header>'+
'<div class="nx360-wrap"><div style="position:relative"><label class="nx360-search"><span>⌕</span><input id="nx360Search" autocomplete="off" placeholder="Buscar cliente por nombre, cédula o teléfono…"></label><div id="nx360Results" class="nx360-results"></div></div>'+
'<section class="nx360-hero"><div id="nx360Avatar" class="nx360-avatar">JP</div><div><h2 id="nx360Nombre">Juan Pérez</h2><p id="nx360Meta">001-1234567-8 · 809-555-1234</p></div><span id="nx360Estado" class="nx360-status">Al día</span></section>'+
'<section class="nx360-kpis"><article class="nx360-kpi"><span>Saldo pendiente</span><strong id="nx360Saldo">—</strong><small>Fuente: Financiamiento</small></article><article class="nx360-kpi"><span>Capital financiado</span><strong id="nx360Capital">—</strong><small>Contrato vigente</small></article><article class="nx360-kpi"><span>Total pagado</span><strong id="nx360Pagado">—</strong><small>Movimientos</small></article><article class="nx360-kpi"><span>Pólizas</span><strong id="nx360Polizas">—</strong><small>Seguros</small></article><article class="nx360-kpi"><span>Facturas</span><strong id="nx360Facturas">—</strong><small>Histórico</small></article></section>'+
'<div class="nx360-tabs" role="tablist"><button class="nx360-tab on" data-tab="resumen">Resumen</button><button class="nx360-tab" data-tab="financiamiento">Financiamiento</button><button class="nx360-tab" data-tab="pagos">Pagos</button><button class="nx360-tab" data-tab="equipos">Equipos</button><button class="nx360-tab" data-tab="seguros">Seguros</button><button class="nx360-tab" data-tab="facturas">Facturas</button><button class="nx360-tab" data-tab="documentos">Documentos</button><button class="nx360-tab" data-tab="actividad">Actividad</button></div>'+
'<section id="nx360Panel" class="nx360-panel on"></section></div></main></div>'+
'<div id="nx360PayBack" class="nx360-back" role="dialog" aria-modal="true" aria-labelledby="nx360PayTitle"><div class="nx360-sheet"><h3 id="nx360PayTitle">Registrar pago</h3><p id="nx360PayCliente" style="color:#64748b;font-size:12px"></p><div class="nx360-field"><label>Monto</label><input id="nx360PayMonto" inputmode="decimal" placeholder="RD$ 0.00"></div><div class="nx360-field"><label>Método</label><select id="nx360PayMetodo"><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option></select></div><div class="nx360-field"><label>Referencia (opcional)</label><input id="nx360PayRef" placeholder="Ej. Pago #123"></div><div class="nx360-actions"><button class="nx360-btn" data-pay-close>Cancelar</button><button class="nx360-btn primary" data-pay-save>Simular pago</button></div></div></div>';
}
function panel(tab){var p=document.getElementById('nx360Panel');if(!p)return;var a=activo;
if(tab==='resumen'){p.innerHTML='<div class="nx360-grid"><article class="nx360-card"><h3>Resumen financiero</h3><div class="nx360-row"><div><b>Préstamo vigente</b><small>Próxima cuota '+esc(a.proxima)+'</small></div><div class="nx360-money">'+fmt(a.saldo)+'<small>'+fmt(a.cuota)+' cuota</small></div></div><div class="nx360-row"><div><b>Comportamiento</b><small>Indicador visual derivado</small></div><span class="nx360-pill">'+esc(a.estado)+'</span></div></article><article class="nx360-card"><h3>Vista 360</h3><div class="nx360-row"><div><b>'+a.equipos+' equipos</b><small>POS / dispositivos</small></div><span>›</span></div><div class="nx360-row"><div><b>'+a.polizas+' pólizas</b><small>Seguros</small></div><span>›</span></div><div class="nx360-row"><div><b>'+a.facturas+' facturas</b><small>Historial comercial</small></div><span>›</span></div></article></div>';
}else if(tab==='financiamiento'){p.innerHTML='<article class="nx360-card"><h3>Financiamiento</h3><div class="nx360-row"><div><b>Préstamo PR-DEMO-001</b><small>Próxima cuota: '+esc(a.proxima)+' · '+fmt(a.cuota)+'</small></div><div class="nx360-money">'+fmt(a.saldo)+'<small>saldo</small></div></div></article>';
}else if(tab==='pagos'){p.innerHTML='<article class="nx360-card"><h3>Pagos</h3><div class="nx360-row"><div><b>Pago reciente</b><small>01 Ago · Efectivo</small></div><div class="nx360-money">'+fmt(Math.min(a.pagado,5000))+'</div></div><div class="nx360-row"><div><b>Histórico acumulado</b><small>Dato simulado para validar UX</small></div><div class="nx360-money">'+fmt(a.pagado)+'</div></div></article>';
}else if(tab==='actividad'){p.innerHTML='<article class="nx360-card"><h3>Actividad del cliente</h3><div class="nx360-row"><div><b>Pago registrado</b><small>01 Ago · Financiamiento</small></div><span class="nx360-pill">Completado</span></div><div class="nx360-row"><div><b>Contacto por WhatsApp</b><small>29 Jul · Seguimiento</small></div><span>›</span></div></article>';
}else{var nombres={equipos:'Equipos',seguros:'Seguros',facturas:'Facturas',documentos:'Documentos'};p.innerHTML='<article class="nx360-card"><h3>'+esc(nombres[tab]||tab)+'</h3><div style="padding:28px;text-align:center;color:#64748b">Vista de alta fidelidad preparada. La conexión al backend se hará después de aprobar la UX.</div></article>';}}
function pintar(){var a=activo;document.getElementById('nx360Avatar').textContent=a.nombre.split(/\s+/).slice(0,2).map(function(x){return x[0]}).join('').toUpperCase();document.getElementById('nx360Nombre').textContent=a.nombre;document.getElementById('nx360Meta').textContent=a.cedula+' · '+a.tel;var e=document.getElementById('nx360Estado');e.textContent=a.estado;e.style.background=a.estado==='En mora'?'#fff7ed':'#ecfdf5';e.style.color=a.estado==='En mora'?'#b45309':'#047857';document.getElementById('nx360Saldo').textContent=fmt(a.saldo);document.getElementById('nx360Capital').textContent=fmt(a.capital);document.getElementById('nx360Pagado').textContent=fmt(a.pagado);document.getElementById('nx360Polizas').textContent=a.polizas;document.getElementById('nx360Facturas').textContent=a.facturas;panel('resumen');}
function cambiarTab(tab){document.querySelectorAll('#nx360Root .nx360-tab').forEach(function(b){b.classList.toggle('on',b.dataset.tab===tab)});panel(tab);}
function buscar(q){q=String(q||'').trim().toLowerCase();var box=document.getElementById('nx360Results');if(!q){box.classList.remove('show');return;}var r=clientes.filter(function(c){return(c.nombre+' '+c.cedula+' '+c.tel).toLowerCase().includes(q)});box.innerHTML=r.length?r.map(function(c){return '<button class="nx360-result" data-client="'+c.id+'"><b>'+esc(c.nombre)+'</b><small style="display:block;color:#64748b">'+esc(c.cedula)+' · '+esc(c.tel)+'</small></button>';}).join(''):'<div style="padding:12px;color:#64748b">Sin resultados en la demo</div>';box.classList.add('show');}
function abrirPago(){var b=document.getElementById('nx360PayBack');document.getElementById('nx360PayCliente').textContent=activo.nombre+' · Saldo '+fmt(activo.saldo);document.getElementById('nx360PayMonto').value=activo.cuota;b.classList.add('show');setTimeout(function(){document.getElementById('nx360PayMonto').focus()},0);}
function cerrarPago(){document.getElementById('nx360PayBack').classList.remove('show');}
function simularPago(){var m=Number(String(document.getElementById('nx360PayMonto').value).replace(/[^0-9.]/g,''));if(!m||m<=0)return alert('Ingrese un monto válido.');alert('Demo visual: no se escribió ningún pago en Supabase.\nMonto simulado: '+fmt(m));cerrarPago();}
function init(){if(document.getElementById('nx360Root'))return;asegurarCSS();var r=document.createElement('div');r.id='nx360Root';r.innerHTML=markup();document.body.appendChild(r);var f=document.createElement('button');f.id='nx360Launcher';f.className='nx360-fab';f.textContent='Cliente 360';f.setAttribute('aria-label','Abrir expediente Cliente 360');document.body.appendChild(f);f.addEventListener('click',function(){window.nx360Abrir()});r.addEventListener('click',function(ev){var t=ev.target.closest('[data-close],[data-tab],[data-client],[data-pay],[data-pay-close],[data-pay-save]');if(!t)return;if(t.hasAttribute('data-close'))return window.nx360Cerrar();if(t.dataset.tab)return cambiarTab(t.dataset.tab);if(t.dataset.client){activo=clientes.find(function(c){return c.id===t.dataset.client})||activo;document.getElementById('nx360Results').classList.remove('show');document.getElementById('nx360Search').value='';return pintar();}if(t.hasAttribute('data-pay'))return abrirPago();if(t.hasAttribute('data-pay-close'))return cerrarPago();if(t.hasAttribute('data-pay-save'))return simularPago();});document.getElementById('nx360Search').addEventListener('input',function(e){buscar(e.target.value)});document.addEventListener('keydown',function(e){if(e.key==='Escape'){if(document.getElementById('nx360PayBack').classList.contains('show'))cerrarPago();else if(r.classList.contains('nx360-open'))window.nx360Cerrar();}});pintar();}
window.nx360Abrir=function(){init();ultimoFoco=document.activeElement;document.getElementById('nx360Root').classList.add('nx360-open');document.body.dataset.nx360Overflow=document.body.style.overflow||'';document.body.style.overflow='hidden';setTimeout(function(){document.getElementById('nx360Search').focus()},0);};
window.nx360Cerrar=function(){var r=document.getElementById('nx360Root');if(!r)return;r.classList.remove('nx360-open');document.body.style.overflow=document.body.dataset.nx360Overflow||'';if(ultimoFoco&&ultimoFoco.focus)ultimoFoco.focus();};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
